### ISSUE TITLE
Herobrine Missing

### ISSUE THREAD

**Issue by Fargus5** [LucasRomier/BetterMobAI#5]
There is no Herobrine in your plugin

**Comment by Fargus5** [comment]
?

**Comment by OpticFusion1** [comment]
Make a new issue at https://github.com/OpticFusion1/BetterMobMechanics/issues (follow the format) please.
(Working on re-doing this plugin, having issues made there which follow a format is easier and better :P)

**Comment by Fargus5** [comment]
never get a fix about this
BetterMobMechanics doesn't not exist
